### ISSUE TITLE
Upgrade 'kind-of' dependency

### ISSUE THREAD

**Issue by musainayatmalik** [medianeuroscience/icore#20]
Advisory on security vulnerability suggests to fix/upgrade 'kind-of' package, used to validate object type. Experiment and do so after updated icore app is fully functioning and bug-free.

**Comment by fhopp** [comment]
@musainayatmalik perhaps we can already incldue the newer version in the new install?

**Comment by fhopp** [comment]
@musainayatmalik what is the state on this?

**Comment by musainayatmalik** [comment]
i'll check how it impacts the functioning of the app on a local copy first. if all goes well, will release upgrade with the addition of the new contact/team page on icore.

**Comment by rene-weber** [comment]
Has this been completed? If yes, please close. If not, please report status here.

**Comment by musainayatmalik** [comment]
node modules have to be removed and reinstalled before updating. However, the update works without breaking icore's functionality. Will be reflected on github once code is pushed to the repo.
