### ISSUE TITLE
Debug script for events retrieval

### ISSUE THREAD

**Issue by musainayatmalik** [medianeuroscience/icore#30]
Name reference bug in events retrieval script that emerged after splitting queries into sublists for parse_gdelt_2020.py

**Comment by musainayatmalik** [comment]
<img width="601" alt="Screen Shot 2020-05-20 at 4 55 32 PM" src="https://user-images.githubusercontent.com/30234006/82508737-d7014280-9aba-11ea-8245-915aca3ab3db.png">

**Comment by fhopp** [comment]
Try now, should be fixed.
