### ISSUE TITLE
Add scraper to ingest script.

### ISSUE THREAD

**Issue by fhopp** [medianeuroscience/icore#5]
Directly scrape articles from websource as GKG record is being parsed.

**Comment by fhopp** [comment]
Scraper has been added, but progress is slow. @musainayatmalik let's sit together an discuss how we can make it faster.

**Comment by musainayatmalik** [comment]
Perfect. Multiple keyspace connections should be the way to go. Based on community experience, seems like a few tables shouldn't make thii technically infeasible. This SO post discusses a similar idea.

https://stackoverflow.com/questions/38972616/is-it-good-practice-to-have-multiple-keyspaces-in-cassandra

**Comment by musainayatmalik** [comment]
Scraper pipeline in place. Optimal for daily ingestion of URLS and update. 

Created a new table "scraped_articles" for storage.

Future feature extraction code can be inserted within this script.

**Comment by fhopp** [comment]
Neat! Closing this now.
