### ISSUE TITLE
Create high-level system overview documentation

### ISSUE THREAD

**Issue by fhopp** [medianeuroscience/icore#8]
Once the new features are implemented, we should create a better documentation of the overall system.

**Comment by fhopp** [comment]
@musainayatmalik , could you please add a section to the sidebar under the label 'Documentation' that links to our documentation pages? Thanks!

**Comment by musainayatmalik** [comment]
documentation, meaning tutorials correct?

**Comment by musainayatmalik** [comment]
implemented this (along with other things that needed to be debugged after our url header resolution success)
